### ISSUE TITLE
feature request: support for reading TIFF

### ISSUE THREAD

**Issue by magicdoublem** [doterax/guetzli-cuda-opencl#2]
Support for reading TIFF would be a good thing to have. Can be left very rudimentary and limited to 8bit/no zip-compression, everything else doesn't make much sense for using it as an intermediate format to bake guetzlis.

**Comment by doterax** [comment]
Looks like [libtiff](http://www.libtiff.org/libtiff.html) is the best option.

**Comment by magicdoublem** [comment]
> Looks like [libtiff](http://www.libtiff.org/libtiff.html) is the best option.

Yes, looks like a promising match.

**Comment by doterax** [comment]
I have just added TIFF support. If you can, try it and let me know what you think.

**Comment by magicdoublem** [comment]
> I have just added TIFF support. If you can, try it and let me know what you think.

Wow, that was fast. It works just fine. I've tried 8bit, 16bit, with and without zip compression and all things worked smoothly.

I just get a "TIFFFetchNormalTag: Warning, Incorrect value for "RichTIFFIPTC"; tag ignored." warning every time. The tag isn't set, the files are coming straight out of LRc.

**Comment by doterax** [comment]
> I just get a "TIFFFetchNormalTag: Warning, Incorrect value for "RichTIFFIPTC"; tag ignored." warning every time.

Could you provide example TIFF file for investigation?

**Comment by magicdoublem** [comment]
> > I just get a "TIFFFetchNormalTag: Warning, Incorrect value for "RichTIFFIPTC"; tag ignored." warning every time.
> 
> Could you provide example TIFF file for investigation?

I narrowed it down to the files for which I used a metadata-preset to set things like copyright-fields. Here's the same tiff with and without that kind of metadata. The one with it gives the error I mentioned above, but encodes fine.
[test_tiffs.zip](https://github.com/doterax/guetzli-cuda-opencl/files/7010018/test_tiffs.zip)

**Comment by doterax** [comment]
This warning is not harmfull. And was supressed in non verbose mode.
