### ISSUE TITLE
add support for --progressive JPEG encoding

### ISSUE THREAD

**Issue by magicdoublem** [doterax/guetzli-cuda-opencl#6]
Since the jpegtran can still chop of some more bytes even from guetzlis and the way pjpegs are loaded by viewers can be a bit superior, especially for bigger/highres-files, it would be nice to add direct support to guetzli itself if doable.

**Comment by doterax** [comment]
I have been playing with jpegtran embeding in guetzli for more than a day. And I think system became more complex than needed. So for now I considering to postpone this. And I recommend running jpegtran after guetzli to maximize effect.

**Comment by magicdoublem** [comment]
Yes, I agree. If it's too complicated to integrate, then running jpegtran afterwards is a good enough solution. Thank you very much for looking into it and trying. 👍🏻
