### ISSUE TITLE
unable to run on non nVidia machine

### ISSUE THREAD

**Issue by crass00** [doterax/guetzli-cuda-opencl#9]
When I try to run this on an Radeon system (using the --auto or --opencl or no switches) I get a popup 

"The code execution cannot proceed becuase nvcuda.dll was not found. Reinstalling the program may fix this problem"

The error itself makes sense since I don't have an nVidia card but I don't beleive that should be required for using the opencl optimized routines

**Comment by doterax** [comment]
Fixed in https://github.com/doterax/guetzli-cuda-opencl/releases/tag/v2.1.5 

Tested on clear windows installation, worked witout problem.

Enjoy.
